blank_issues_enabled: false
contact_links:
    -   name: ðŸ’¬ Discussions
        url: https://github.com/l0uisgrange/zap/discussions
        about: Ask questions and discuss ideas with the community
    -   name: ðŸ“š Documentation
        url: https://zap.grangelouis.ch
        about: Check the official documentation for usage guides and API reference
